pipeline:
  identifier: Build_Qwiet_js_GH_1696007603542
  name: Build Qwiet-js-GH
  orgIdentifier: default
  projectIdentifier: QwietjsHarn
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1696007572273
        repoName: ongamse/Qwiet-js-GH
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    connectorRef: account.harnessImage
                    image: plugins/docker
                    settings:
                      dry_run: "true"
                      repo: hello/world
                      tags: latest
                  timeout: ""
                  type: Plugin
              - step:
                  identifier: npminstall
                  name: npm_install
                  spec:
                    shell: Sh
                    command: npm install
                  timeout: ""
                  type: Run
              - step:
                  type: Run
                  name: Qwiet
                  identifier: Qwiet
                  spec:
                    shell: Sh
                    command: |-
                      #Download Qwiet
                      curl https://cdn.shiftleft.io/download/sl >/usr/local/bin/sl && chmod a+rx /usr/local/bin/sl
                      #Run Qwiet
                      sl analyze --app TestHarness --js .
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
