pipeline:
  identifier: Build_Qwiet_js_GH_1696007603542
  name: Build Qwiet-js-GH
  orgIdentifier: default
  projectIdentifier: QwietjsHarn
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1696007572273
        repoName: ongamse/Qwiet-js-GH
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    connectorRef: account.harnessImage
                    image: plugins/docker
                    settings:
                      dry_run: "true"
                      repo: hello/world
                      tags: latest
                  timeout: ""
                  type: Plugin
              - step:
                  identifier: npminstall
                  name: npm_install
                  spec:
                    shell: Sh
                    command: npm install
                  timeout: ""
                  type: Run
              - step:
                  type: Run
                  name: Qwiet
                  identifier: Qwiet
                  spec:
                    shell: Sh
                    command: |-
                      #QwietToken
                      echo "project var: " <+variable.proj_var>
                      #Download Qwiet
                      curl https://cdn.shiftleft.io/download/sl >/usr/local/bin/sl && chmod a+rx /usr/local/bin/sl
                      #Run Qwiet
                      sl analyze --app Qwiet-js-Harness --js .
                    envVariables:
                      SHIFTLEFT_ACCESS_TOKEN: eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Njg1NTE1MzksImlzcyI6IlNoaWZ0TGVmdCIsIm9yZ0lEIjoiMzc4NDViODQtMGYyYi00ZmZkLWIxNjAtNDEzNTFkODBjMjFkIiwidXNlcklEIjoiOTQ4Mjc4ZmUtODA2YS00YWU0LWFiNDQtMzRhNzZmMjgzMDEyIiwic2NvcGVzIjpbInNlYXRzOndyaXRlIiwiZXh0ZW5kZWQiLCJhcGk6djIiLCJ1cGxvYWRzOndyaXRlIiwibG9nOndyaXRlIiwicGlwZWxpbmVzdGF0dXM6cmVhZCIsIm1ldHJpY3M6d3JpdGUiLCJwb2xpY2llczpjdXN0b21lciIsInBvbGljaWVzOnJlYWQiXX0.NhoUPyh8SBUWC0hemSrlp4prTLe8OSTICTc1r69wTk27xeu7AqkurkJ7yyGfdUH_hdFLTlGIZR9CyyCSrgWVXSCds8zPRE8Qk8mq_5cBdBpX9NM3O3RLNOp6VVchGI6dFX1QyMf2LoajzCZDdCvfssgJdej9ILXX_fBgIuG9svfMOEUMSeaamM1Q7hK6PD0b1oWG0Xn6isZ9Mf_IVvUsYeSAEJxKT8NSWh0zPqUgw-7GOwW3bQOSh23RcfIxGKmFqXhmkGzl_ttFT-fPeNJKipW3JP_Vr0LM389Tk7UwrTsMIGFMJC7mpxFcoAPG6kCpjHi_NfOYr4cxRJdbNznuIA
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
